### ISSUE TITLE
Use the database created on postgres startup

### ISSUE THREAD

**Issue by debuglevel** [jfederico/greenlight-run#7]
This creates the database if it does not exist. But the postgres image does already create a database for us on first startup.
```
db_create="$(RAILS_ENV=$RAILS_ENV bundle exec rake db:create 2>&1)"
echo $db_create
```

If it did not already exist, the schema will be loaded:
```
if [[ $db_create != *"already exists"* ]]; then
  echo ">>> Database initialization"
  bundle exec rake db:schema:load
fi
```

But if an empty database did already exist, the schema will not be loaded.

This is an issue if one uses an usual Docker Postgres setup which already creates an empty database:
```
  postgres:
    image: postgres:14
    environment:
      POSTGRES_DB: greenlight
      POSTGRES_USER: greenlight
      POSTGRES_PASSWORD: greenlight
```
(The setup used in this repository creates an empty useless `postgres` database.)
